spring.application.name=Tournament 


#SQL database connection details

spring.datasource.url=jdbc:postgresql://localhost:5432/tournamentdb
spring.datasource.username=postgres
spring.datasource.password=Vaibhav143

#DDL Generation
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true